# Generated by Django 2.2.4 on 2019-08-17 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_begin_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hover_position', models.CharField(choices=[('T', 'Top'), ('B', 'Bot'), ('L', 'Left'), ('R', 'Rigth')], default='T', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userextended', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
