# Generated by Django 2.2.4 on 2019-08-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astaykov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
